package calculadoranetbeans;

import java.text.NumberFormat;
import java.text.ParseException;

public class CalculadoraGUI extends javax.swing.JFrame {

    private CalculadoraController calculadoraController;
    private EnumOperacao ultimaOperacao;
    private boolean resultadoExibido = false;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
        calculadoraController = new CalculadoraController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValor = new javax.swing.JTextField();
        pTeclas = new javax.swing.JPanel();
        btCE = new javax.swing.JButton();
        btAC = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();
        btDivisao = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btMultiplicacao = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btSubtracao = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btSoma = new javax.swing.JButton();
        btMaisMenos = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora POO");
        setBackground(new java.awt.Color(60, 60, 60));
        setLocation(new java.awt.Point(0, 0));

        tfValor.setEditable(false);
        tfValor.setBackground(new java.awt.Color(60, 60, 60));
        tfValor.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tfValor.setForeground(new java.awt.Color(255, 255, 255));
        tfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValor.setText("0");
        tfValor.setActionCommand("<Not Set>");
        tfValor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfValor.addActionListener(this::tfValorActionPerformed);

        pTeclas.setLayout(new java.awt.GridLayout(5, 4));

        btCE.setBackground(new java.awt.Color(43, 43, 43));
        btCE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCE.setForeground(new java.awt.Color(255, 255, 255));
        btCE.setText("CE");
        btCE.addActionListener(this::btCEActionPerformed);
        pTeclas.add(btCE);

        btAC.setBackground(new java.awt.Color(43, 43, 43));
        btAC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAC.setForeground(new java.awt.Color(255, 255, 255));
        btAC.setText("AC");
        btAC.addActionListener(this::btACActionPerformed);
        pTeclas.add(btAC);

        btApagar.setBackground(new java.awt.Color(43, 43, 43));
        btApagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btApagar.setForeground(new java.awt.Color(255, 255, 255));
        btApagar.setText("<---");
        pTeclas.add(btApagar);

        btDivisao.setBackground(new java.awt.Color(43, 43, 43));
        btDivisao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDivisao.setForeground(new java.awt.Color(255, 255, 255));
        btDivisao.setText("/");
        btDivisao.addActionListener(this::btDivisaoActionPerformed);
        pTeclas.add(btDivisao);

        bt7.setBackground(new java.awt.Color(60, 60, 60));
        bt7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt7.setForeground(new java.awt.Color(255, 255, 255));
        bt7.setText("7");
        bt7.addActionListener(this::bt7ActionPerformed);
        pTeclas.add(bt7);

        bt8.setBackground(new java.awt.Color(60, 60, 60));
        bt8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt8.setForeground(new java.awt.Color(255, 255, 255));
        bt8.setText("8");
        bt8.addActionListener(this::bt8ActionPerformed);
        pTeclas.add(bt8);

        bt9.setBackground(new java.awt.Color(60, 60, 60));
        bt9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt9.setForeground(new java.awt.Color(255, 255, 255));
        bt9.setText("9");
        bt9.addActionListener(this::bt9ActionPerformed);
        pTeclas.add(bt9);

        btMultiplicacao.setBackground(new java.awt.Color(43, 43, 43));
        btMultiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btMultiplicacao.setForeground(new java.awt.Color(255, 255, 255));
        btMultiplicacao.setText("X");
        btMultiplicacao.addActionListener(this::btMultiplicacaoActionPerformed);
        pTeclas.add(btMultiplicacao);

        bt4.setBackground(new java.awt.Color(60, 60, 60));
        bt4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 255, 255));
        bt4.setText("4");
        bt4.addActionListener(this::bt4ActionPerformed);
        pTeclas.add(bt4);

        bt5.setBackground(new java.awt.Color(60, 60, 60));
        bt5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt5.setForeground(new java.awt.Color(255, 255, 255));
        bt5.setText("5");
        bt5.addActionListener(this::bt5ActionPerformed);
        pTeclas.add(bt5);

        bt6.setBackground(new java.awt.Color(60, 60, 60));
        bt6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt6.setForeground(new java.awt.Color(255, 255, 255));
        bt6.setText("6");
        bt6.addActionListener(this::bt6ActionPerformed);
        pTeclas.add(bt6);

        btSubtracao.setBackground(new java.awt.Color(43, 43, 43));
        btSubtracao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btSubtracao.setForeground(new java.awt.Color(255, 255, 255));
        btSubtracao.setText("-");
        btSubtracao.addActionListener(this::btSubtracaoActionPerformed);
        pTeclas.add(btSubtracao);

        bt1.setBackground(new java.awt.Color(60, 60, 60));
        bt1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("1");
        bt1.addActionListener(this::bt1ActionPerformed);
        pTeclas.add(bt1);

        bt2.setBackground(new java.awt.Color(60, 60, 60));
        bt2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("2");
        bt2.addActionListener(this::bt2ActionPerformed);
        pTeclas.add(bt2);

        bt3.setBackground(new java.awt.Color(60, 60, 60));
        bt3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("3");
        bt3.addActionListener(this::bt3ActionPerformed);
        pTeclas.add(bt3);

        btSoma.setBackground(new java.awt.Color(43, 43, 43));
        btSoma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSoma.setForeground(new java.awt.Color(255, 255, 255));
        btSoma.setText("+");
        btSoma.addActionListener(this::btSomaActionPerformed);
        pTeclas.add(btSoma);

        btMaisMenos.setBackground(new java.awt.Color(60, 60, 60));
        btMaisMenos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btMaisMenos.setForeground(new java.awt.Color(255, 255, 255));
        btMaisMenos.setText("+/-");
        pTeclas.add(btMaisMenos);

        bt0.setBackground(new java.awt.Color(60, 60, 60));
        bt0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt0.setForeground(new java.awt.Color(255, 255, 255));
        bt0.setText("0");
        bt0.addActionListener(this::bt0ActionPerformed);
        pTeclas.add(bt0);

        btFechar.setBackground(new java.awt.Color(60, 60, 60));
        btFechar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btFechar.setForeground(new java.awt.Color(255, 255, 255));
        btFechar.setText("FECHAR");
        btFechar.addActionListener(this::btFecharActionPerformed);
        pTeclas.add(btFechar);

        btResultado.setBackground(new java.awt.Color(43, 43, 43));
        btResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResultado.setForeground(new java.awt.Color(255, 255, 255));
        btResultado.setText("=");
        btResultado.addActionListener(this::btResultadoActionPerformed);
        pTeclas.add(btResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfValor)
                    .addComponent(pTeclas, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTeclas, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed

    }//GEN-LAST:event_tfValorActionPerformed

    private void btCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCEActionPerformed

    private void btSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomaActionPerformed
        calculadoraController.realizaOperacao(EnumOperacao.SOMA, stringToInteger(tfValor.getText()));
        ultimaOperacao = EnumOperacao.SOMA;
        limpa();
    }//GEN-LAST:event_btSomaActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        digita("3");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        digita("0");
    }//GEN-LAST:event_bt0ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        digita("1");
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        digita("2");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        digita("4");
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        digita("5");
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        digita("6");
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        digita("7");
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        digita("8");
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        digita("9");
    }//GEN-LAST:event_bt9ActionPerformed

    private void btACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btACActionPerformed
        calculadoraController.zerar();
        limpa();
    }//GEN-LAST:event_btACActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btFecharActionPerformed

    private void btSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtracaoActionPerformed
        calculadoraController.realizaOperacao(EnumOperacao.SUBTRACAO, stringToInteger(tfValor.getText()));
        ultimaOperacao = EnumOperacao.SUBTRACAO;
        limpa();
    }//GEN-LAST:event_btSubtracaoActionPerformed

    private void btMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplicacaoActionPerformed
        calculadoraController.realizaOperacao(EnumOperacao.MULTIPLICACAO, stringToInteger(tfValor.getText()));
        ultimaOperacao = EnumOperacao.MULTIPLICACAO;
        limpa();
    }//GEN-LAST:event_btMultiplicacaoActionPerformed

    private void btDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivisaoActionPerformed
        calculadoraController.realizaOperacao(EnumOperacao.DIVISAO, stringToInteger(tfValor.getText()));
        ultimaOperacao = EnumOperacao.DIVISAO;
        limpa();
    }//GEN-LAST:event_btDivisaoActionPerformed

    private void btResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResultadoActionPerformed
        Integer resultado = calculadoraController.realizaOperacao(ultimaOperacao, stringToInteger(tfValor.getText()));
        tfValor.setText(integerToString(resultado));
        System.out.println("Resultado da operacao: " + integerToString(resultado));
        calculadoraController.preparaParaProximaOperacao();
        resultadoExibido = true;
    }//GEN-LAST:event_btResultadoActionPerformed

    private Integer stringToInteger(String numero) {
        NumberFormat nf = NumberFormat.getInstance();
        Integer dv = 0;
        try {
            dv = nf.parse(numero).intValue();
        } catch (ParseException ex) {

        }
        return dv;
    }

    private String integerToString(Integer numero) {
        if (numero != null) {
            return String.valueOf(numero);
        }
        return "";
    }

    private void limpa() {
        tfValor.setText("0");
        resultadoExibido = false;
    }

    private void digita(String caractere) {
        String textoAtual = tfValor.getText();

        if (resultadoExibido) {
            tfValor.setText(caractere);
            resultadoExibido = false;
        } else if (textoAtual.equals("0")) {
            tfValor.setText(caractere);
        } else if (textoAtual.length() < 3) {
            tfValor.setText(textoAtual.concat(caractere));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAC;
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btCE;
    private javax.swing.JButton btDivisao;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btMaisMenos;
    private javax.swing.JButton btMultiplicacao;
    private javax.swing.JButton btResultado;
    private javax.swing.JButton btSoma;
    private javax.swing.JButton btSubtracao;
    private javax.swing.JPanel pTeclas;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

    private class CalculadoraController {

        private Integer total;
        boolean primeiraOperacao = true;

        public CalculadoraController() {
            total = 0;
        }

        public Integer realizaOperacao(EnumOperacao operacao, Integer valor) {

            if (primeiraOperacao) {
                total = valor;
                primeiraOperacao = false;
            } else if (!primeiraOperacao) {
                
                if (operacao.equals(EnumOperacao.SOMA)) {
                    total += valor;
                } else if (operacao.equals(EnumOperacao.SUBTRACAO)) {
                    total -= valor;
                } else if (operacao.equals(EnumOperacao.MULTIPLICACAO)) {
                    total *= valor;
                } else if (operacao.equals(EnumOperacao.DIVISAO)) {
                    total /= valor;
                }
            }

            return total;
        }

        public Integer getTotal() {
            return this.total;
        }

        public void zerar() {
            total = 0;
            primeiraOperacao = true;
        }

        public void preparaParaProximaOperacao() {
            primeiraOperacao = true;
        }

    }

    public enum EnumOperacao {
        SOMA,
        SUBTRACAO,
        MULTIPLICACAO,
        DIVISAO;
    }

}
