/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoranetbeans;

/**
 *
 * @author richa
 */
public class CalculadoraGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValor = new javax.swing.JTextField();
        pTeclas = new javax.swing.JPanel();
        btCE = new javax.swing.JButton();
        btAC = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();
        btDivisao = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btMultiplicacao = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btSubtracao = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btSoma = new javax.swing.JButton();
        btMaisMenos = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora POO");

        tfValor.setEditable(false);
        tfValor.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValor.setText("0.00");
        tfValor.setActionCommand("<Not Set>");
        tfValor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfValor.addActionListener(this::tfValorActionPerformed);

        pTeclas.setLayout(new java.awt.GridLayout(5, 4));

        btCE.setText("CE");
        btCE.addActionListener(this::btCEActionPerformed);
        pTeclas.add(btCE);

        btAC.setText("AC");
        btAC.addActionListener(this::btACActionPerformed);
        pTeclas.add(btAC);

        btApagar.setText("<---");
        pTeclas.add(btApagar);

        btDivisao.setText("/");
        pTeclas.add(btDivisao);

        bt7.setText("7");
        bt7.addActionListener(this::bt7ActionPerformed);
        pTeclas.add(bt7);

        bt8.setText("8");
        bt8.addActionListener(this::bt8ActionPerformed);
        pTeclas.add(bt8);

        bt9.setText("9");
        bt9.addActionListener(this::bt9ActionPerformed);
        pTeclas.add(bt9);

        btMultiplicacao.setText("X");
        pTeclas.add(btMultiplicacao);

        bt4.setText("4");
        bt4.addActionListener(this::bt4ActionPerformed);
        pTeclas.add(bt4);

        bt5.setText("5");
        bt5.addActionListener(this::bt5ActionPerformed);
        pTeclas.add(bt5);

        bt6.setText("6");
        bt6.addActionListener(this::bt6ActionPerformed);
        pTeclas.add(bt6);

        btSubtracao.setText("-");
        pTeclas.add(btSubtracao);

        bt1.setText("1");
        bt1.addActionListener(this::bt1ActionPerformed);
        pTeclas.add(bt1);

        bt2.setText("2");
        bt2.addActionListener(this::bt2ActionPerformed);
        pTeclas.add(bt2);

        bt3.setText("3");
        bt3.addActionListener(this::bt3ActionPerformed);
        pTeclas.add(bt3);

        btSoma.setText("+");
        btSoma.addActionListener(this::btSomaActionPerformed);
        pTeclas.add(btSoma);

        btMaisMenos.setText("+/-");
        pTeclas.add(btMaisMenos);

        bt0.setText("0");
        bt0.addActionListener(this::bt0ActionPerformed);
        pTeclas.add(bt0);

        btFechar.setText("Fechar");
        btFechar.addActionListener(this::btFecharActionPerformed);
        pTeclas.add(btFechar);

        btResultado.setText("=");
        pTeclas.add(btResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfValor)
                    .addComponent(pTeclas, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTeclas, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        
    }//GEN-LAST:event_tfValorActionPerformed

    private void btCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCEActionPerformed

    private void btSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSomaActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        digita("3");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        digita("0");
    }//GEN-LAST:event_bt0ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        digita("1");
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        digita("2");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        digita("4");
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        digita("5");
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        digita("6");
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        digita("7");
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        digita("8");
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        digita("9");
    }//GEN-LAST:event_bt9ActionPerformed

    private void btACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btACActionPerformed
        limpa();
    }//GEN-LAST:event_btACActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btFecharActionPerformed
    
    private void limpa(){
        tfValor.setText("0.00");
    }
    
    private void digita(String caractere){
        if(tfValor.getText().equals("0.00")){
            tfValor.setText(caractere);
        } else {
    
            if(tfValor.getText().length() <= 2) {
                tfValor.setText(tfValor.getText().concat(caractere));
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAC;
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btCE;
    private javax.swing.JButton btDivisao;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btMaisMenos;
    private javax.swing.JButton btMultiplicacao;
    private javax.swing.JButton btResultado;
    private javax.swing.JButton btSoma;
    private javax.swing.JButton btSubtracao;
    private javax.swing.JPanel pTeclas;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
